name: busniess_card_app

description: Final year Project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # firebase
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  firebase_dynamic_links: ^2.0.9
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.0+3
  # flutter_facebook_auth: ^3.5.3

  # UI
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  lottie: ^1.2.1
  animated_theme_switcher: ^2.0.1
  # flare_flutter: ^3.0.2
  # rive: ^0.7.28

  # State Management
  get: ^4.6.5
  
  # Utils
  url_strategy: ^0.2.0
  salomon_bottom_bar: ^3.1.0
  flutter_slidable: ^0.6.0
  drag_drop_gridview:
    git:
      url: https://github.com/DholaSain/drag_and_drop_gridview
  reorderables: ^0.4.1
  permission_handler: ^8.1.6
  image_picker: ^0.8.4+2
  qr_flutter: ^4.0.0
  image_gallery_saver: ^1.7.0
  screenshot: ^1.2.3
  share: ^2.0.4
  url_launcher: ^6.0.12
  
  # NFC
  nfc_manager: ^3.2.0
  

  # drag_and_drop_gridview: ^1.0.8
  # url_strategy: ^0.2.0
  # get_it: ^6.1.1
  
  # stacked: ^1.6.0
  shelf_proxy: ^1.0.1
  shelf: ^1.2.0
  # flutter_facebook_login: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.10+1

flutter_icons:
  image_path: "assets/images/appIcon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/appIcon-back.png"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/
   
flutter_native_splash:
  color: "#C81C78"
  image: assets/images/appIcon.png
  image_dark: assets/images/appIcon.png

  android: true
  ios: true
  web: true
 
  fullscreen: true
  android12: true