// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO7DxiO1Usiuh-EOpfH0Y3uvhs98aFBJQ',
    appId: '1:734985929061:web:44e81c144e1eae08a0218c',
    messagingSenderId: '734985929061',
    projectId: 'final-year-project-fd15d',
    authDomain: 'final-year-project-fd15d.firebaseapp.com',
    storageBucket: 'final-year-project-fd15d.appspot.com',
    measurementId: 'G-2PPJQNE9H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCud2tS3yadaVT1YqmscSBmdVT_hEZz5Ew',
    appId: '1:734985929061:android:44c75f35743fcfeaa0218c',
    messagingSenderId: '734985929061',
    projectId: 'final-year-project-fd15d',
    storageBucket: 'final-year-project-fd15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtoukPyDSbE2O_iOgI3Y2i4SpbQCAbMfk',
    appId: '1:734985929061:ios:29bfaf88860ca4aca0218c',
    messagingSenderId: '734985929061',
    projectId: 'final-year-project-fd15d',
    storageBucket: 'final-year-project-fd15d.appspot.com',
    androidClientId: '734985929061-mii6t9i05ueq2fjg3gee08pcrf401rm0.apps.googleusercontent.com',
    iosClientId: '734985929061-jv7bmrm2k4f7di2vb8eekcqsfhm30ccr.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessCardApp',
  );
}
